# These are supported funding model platforms

github: [nikeedev]
patreon: # Replace with a single Patreon username
ko_fi: # Replace with a single Ko-fi username
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry

